bower.json, daterangepicker.js, package.json
Fixes issue https://github.com/dangrossman/bootstrap-daterangepicker/issues/526
=> issue-526: minDate and maxDate aren't respected by inputs

daterangepicker-bs2.css, daterangepicker-bs3.css, daterangepicker.js, examples.html
Added **drop** option (defaults to "down") to control whether the picker opens "down" as usual or "up" (above the picker's button)
=> Allow the picker to drop "up"

daterangepicker.js
=> Fix setOptions

daterangepicker.js
Add an auto apply option that hides the apply and cancel buttons, and immediately notifies callback when calendar dates change (default is false)
=> Add autoApply option

bower.json
allow more recent versions of moment.js
=> allow more recent versions of moment.js

daterangepicker.js
=> when used in ember app a _super function gets added to classes string

daterangepicker.js
To ensure plugin doesn't break server-side rendering
=> check window exists before binding

daterangepicker.css
**Small**
**Medium**
**Large**
=> Tweak the look of the calendar when used on smaller screens

daterangepicker.js
Add support unicode chars in range names.
=> Support unicode chars in range names.

daterangepicker.js
Added return object DateRangePicker in factoory, because in the main function is assignment statement
=> Added return object DateRangePicker  in factoory

daterangepicker.js
Reverts dangrossman/bootstrap-daterangepicker#985
=> Revert "Fix issue in linkedCalendars, where if the maxDate is this month, the…"

daterangepicker.css, daterangepicker.js, daterangepicker.scss, demo.html
Hey :)
This pull request adds RTL support. Modified the demo.html also to add the RTL option to config generator.
=> RTL support

daterangepicker.js
This makes the two inputs look a lot more bootstrappy. Change is illustrated here https://i.imgur.com/Ge1usND.png
=> Add .form-control to calendar inputs

daterangepicker.js
=> Get initial format from Moment.js

daterangepicker.js
- Close datepicker when hitting ESC
=> Hide datepicker when hitting ESC key

website/website.js
The current config generator produces config code which contains a typo in the console.log line. Fixed it.
=> fixed config generator code string quotes

daterangepicker.js
=> Clone start/end dates before passing to callback

website/index.html
If so, then on docs page also should reflected.
=> cancelButtonClasses right?

daterangepicker.js
See http://api.jquery.com/text-selector/
=> use the `:text` selector instead of `input[type=text]`

daterangepicker.js
Fix for maxDate.month is not a function and minDate.month is not a function
=> Bug with minYear & maxYear without min/max Date

daterangepicker.js
fix: https://github.com/dangrossman/daterangepicker/issues/1813
=> 1813: Wrong rendering for the time picker when using maxDate and maxSpan
