daterangepicker.js
Added a validation for the end date when selecting a custom start date,
which added to the actual difference could end up being bigger than the
max date configuratoion.
=> Fix end date bigger than max date

daterangepicker.js
date is not a valid JSDoc block tag, thus it issues warning while minifying (tested with Google closure)
i propose to remove it.
=> Remove invalid date in JSDoc

daterangepicker.js
There are currently three issues with the year dropdown when selecting
a custom range.
To reproduce the errors, use the following fiddle url
http://jsfiddle.net/vitorbarbosa/acozzy2z/ .
1. When changing the left calendar dropdown to year 2014 it does not
respect the assigned minDate. Although it correctly shows the minDate
month in the dropdown (june 2014), it is showing the february month
calendar (log as you will but you quickly can see that the month in the
calendar has 28 days).
2. It does not respect the assigned start date when you select the same
year in the right calendar dropdown. Although it correctly shows the
start date month in the dropdown, it is showing the wrong month
calendar. To reproduce, select 01 August 2014 in the left calendar.
When changing the right calendar to …
=> Fix year dropdown issues

daterangepicker.js
Whenever endDate becomes bigger than maxDate, it is set to maxDate without cloning the object. This results in maxDate being modified every time endDate is updated.
=> Fix unwanted endDate modifying maxDate.

daterangepicker.js
This change lets keyboard centric users use the [tab] key to tab out of daterangepicker controls.
This "fixed" this issue [574](https://github.com/dangrossman/bootstrap-daterangepicker/issues/574) for me.
=> Added keydown function to hide on tab(9) and enter(13).

daterangepicker.js
We noticed that when setting `dateLimit`, the calendar will enforce the limit by updating the "other" date when the `dateLimit` is exceeded, but when inputting dates manually in the date range text boxes, the "other" date is not updated. This allows a date range that exceeds the `dateLimit` to be applied.
This change makes the behavior of manually inputting dates outside the dateLimit consistent with selecting dates outsidet the dateLimit on the calendar by updating the "other" text input when a manual input change makes the date range exceed the `dateLimit`.
=> add dateLimit logic to input change flow. 

daterangepicker.js
Detected a problem that the manual selected moment object is in UTCtime
Issue: #626
=> possible patch for issue #626

daterangepicker.js
This allows the picker to be aligned on a direction other than the default right
=> Allows singleDatePicker to appear left, right or centered

daterangepicker.js
<button> will implicitly submit, which can cause problems if you want to use a button in a form without it submitting. So I think buttons should have attribute type="button".
=> Set atribute type button for html button to prevent form submit.

README.md, daterangepicker.js
Sometimes it's necessary to set options without modifying the javascript. This pull request adds the flexibility to allow setting options through HTML5 data attributes.
This also eases the transition for people coming from bootstrap datetimepicker who already have existing code which uses data attributes: http://eonasdan.github.io/bootstrap-datetimepicker/#example5
This addresses issue #195
=> Allow setting options with HTML5 data attributes

package.json
These engines aren't used anywhere anyway and give a confusing warning when `npm install`-ing.
=> Remove unnecessary engine version restrictions in package.json

daterangepicker.js
If two predefined ranges match the selected range, both are highlighted and it looks awkward:
This change only highlights the first predefined range.
=> only highlight first predefined range

daterangepicker.js
I am attempting to bring one of the Angular Bootstrap Date range picker directives up to the latest version of bootstrap-daterangepicker. However, the library currently auto updates the input value upon initialization and hiding of the date range picker. This has adverse affects on the Angular model system. This pull-request addresses that by adding an option to disable this automatic update of the input (but leaves it on by default, of course).
=> Adding option to disable auto updating the attached text input

daterangepicker.js
This undeclared variable causes an error if this file is included in strict environments. Also, the undeclared variable was leaking data into the global context.
=> Declare `html` var. 

daterangepicker.js
guard against the implicit use of window (this) which doesn't exist on a server to help with isomorphism
=> only use `this` if it exists

daterangepicker.js
If defined time settings on the range selector they are preserved across multiple selections.
=> Keep the time settings on the right side instead of using the left side one

daterangepicker.js
I have used `daterangepicker` with the custom template that contain `angular` directive. To make angular binding in my template work, it has to be compiled (to be jQuery object) using `$compile` from angular as `{ template: $compile(templateSring)(scope) }`.
I created this PR as it might useful for those who using this `daterangepicker` with Angular app.
=> Make template options to be complied jquery object

package.json
Using a caret version in package.json only allows minor, and patch updates. https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4
=> make package.json and bower.json agree on jquery version

.gitignore, daterangepicker.css, daterangepicker.scss, package.json
Integrating a datepicker in to a design has always been terrible. Either the datepicker itself sucks, or styling is impossible because the resultant markup is so freakin' complex.
Luckily, daterangepicker solves on of these problems. This PR solves the other (part way, anyway).
I've also added the relevant tools to NPM to make builds super simple.
**Note:** Two caveats for this PR.
1. I've only tested this in a few configurations, so I can't guarantee that everything has been perfectly ported.
1. I've left some comments/todo's in the SCSS for things that I'm not totally sure about or think need improvement.
=> SASS-ify the stylesheet

package.js
This allows apps that integrate bootstrap via a different package, for example nemo64:bootstrap, to not be forced to install twbs:bootstrap
=> only weakly require twbs:bootstrap

daterangepicker.js
when the option "singleDatePicker" is true, all icons selected by ".daterangepicker_input i" are hidden. this includes the time icon, which is displayed when the "timePicker" option is true. This fix just hides the "calendar" icon.
=> singleDatePicker no longer hides the time icon

website/website.js
All available locale options should probably be included in the example locale. Currently it seems to include all options except `weekLabel`.
=> Add locale.weekLabel option to example

daterangepicker.js
When you configure the date range with Predefined Ranges and a dateLimit, momentjs shows a  deprecation warning because in the line 318 we have this:
_**this.dateLimit && start.clone().add(this.dateLimit).isAfter(maxDate)**_
In this specific case **maxDate** is false
=> Fixing Momentjs deprecation warning

daterangepicker.js
@dangrossman This fixes some problems when using `minDate`/`maxDate` and programmatically updating `startDate`/`endDate` via `setStartDate`/`setEndDate`.
=> Clone minDate/maxDate variable when assigning to startDate/endDate variable

daterangepicker.css, daterangepicker.scss
Using "background" CSS property overrides Bootstrap styling, specifically the "background-clip: padding-box". This PR fixes that.
=> Change "background" to "background-color" to preserve Bootstrap "background-clip"

daterangepicker.js
I had a problem when using danish characters in the custom range label that the match 
label == this.locale.customRangeLabel
in the hoverRange event caused the error 
Uncaught TypeError: Cannot read property '0' of undefined
at DateRangePicker.hoverRange (daterangepicker.js:1140)
The line var label = e.target.getAttribute('data-range-key'); gave "Vælg interval", whereas this.locale.customRangeLabel has the value "V&#230;lg interval". 
I've solved it by using the same approach as for allowing unicode characters in the labels of the fixed intervals.
=> Adding support for unicode characters in the customrangelabel

daterangepicker.js
the `!this.endDate` was causing the date picker with `timePicker` and `timePicker24Hour` parameters to reset the hour time dropdown to `0`.
You can reproduce it in the demo page as well.
I believe this bug was introduced in the latest release and previous versions didn't have this issue, please consider high priority for this issue.
@dangrossman can you verify please?
=> Time is not being preserved when timepicker was enabled

daterangepicker.js
Some applications may have an odd-ball configuration set up with SystemJS or whatever there module loader could be and already have moment.js included and this prevents it from loading twice in those configurations.
This repeats the practice we're already doing with loading JQuery.
=> Include moment.js only if it does not already exist in window.

daterangepicker.js
This fixes the same thing as #816 but for webpack (https://github.com/skratchdot/react-bootstrap-daterangepicker/issues/43)
=> stub jquery.fn to fix webpack server rendering

daterangepicker.js
When a date like "4 May 2017" is selected from the datepicker and the user attempts to update manually the input to "4 May 2018", the datepicker doesn't respond.
There is a function that handles the keyup events on the corresponding input and performs validations before updating the datepicker value.
```
if (!this.element.is('input')) return;
if (!this.element.val().length) return;
if (this.element.val().length < this.locale.format.length) return;
```
In the third case, it checks the length of the datepicker's selected format (in our case "D MMMM YYYY" the length is 11) against the length of the input value (i.e. "4 May 2018", with length 10). As a result, the datepicker considers the new value as invalid.
I think, a more appropriate approach is to use moment.isValid function in order to …
=> Datepicker not updating when changing the input value

daterangepicker.js
As we cannot set default options yet #1509 , I commit this to enable default options via calling `$.fn.daterangepicker.defaultOptions = { ... };`
=> Add default options

daterangepicker.js
When you enter a date in the start/end date inputs and you press the 'enter' key, the calendar would then update with the range specified in the inputs. This works in Chrome/Firefox/Edge but not in IE 11. This change is to make this behaviour consistent across these major browsers.
As to the cause of this issue, I think it's down to the different browsers triggering the onChange event for inputs on different things. It seems that Chrome/Firefox/Edge will trigger the event when the 'enter' key is pressed as well as when the focus is lost on the input. Whereas IE 11 would only trigger the onChange event when focus is lost on the input. 
I know that this may be a bit specific of a change for IE 11 (which admittedly is because we need to support it for our clients), but this change means that …
=> Ensure that pressing the 'enter' key in the daterange inputs leads to consistent behaviour across major browsers

daterangepicker.js
>options.timePicker does not allow second selection so calculatingChosenLabel did not work for labels with seconds
>Updated calculateChosenLabel so that it works with options.timePicker or option.timPickerSeconds enabled
=> Update calculateChosenLabel to work with timepickerSeconds

daterangepicker.js
Only define a global when AMD and CommonJS detection fail.
This means that `daterangepicker` will no longer be available in the global namespace when the module is loaded by an AMD loader such as via RequireJS. This was already the case in CommonJS environments.
This is a breaking change for users AMD users who were relying on the global although that may be unlikely as the primary use case appears to be use as a jQuery plugin.
This enables proper isolation of dependencies and support for multiple versions of this library, for example as transitive dependencies of other libraries, to properly coexist.
Resolves #1578
=> Only define a global when AMD and CommonJS detection fail

daterangepicker.js
I realized this 'cause 15 oct 2017 was the first day of daylight saving time in Brazil and my app fails there.
I found the problem is because an issue with endOf('day') moment function (moment/moment#3132), that still open there.
So I figured out how to deal with it by myself work around with the logic in datarangepicker.js.
=> Fix for issue #1587

daterangepicker.css, daterangepicker.js
`calendar` is such a generic class name that it conflicts with other components.
=> Rename the `calendar` CSS class to avoid conflicts

daterangepicker.js
With the timePicker option enabled, if you have two labels (for example "last 12 hours" and "last 24 hours") and their start times happen to differ by 12 hours but are in the same day (yesterday at 10 AM and yesterday at 10 PM), the current master will always show "last 12 hours" as selected, even if the range is 24 hours.
This patch changes the format for comparing the currently selected range with labels in the picker so that 24-hour times are used, ensuring this doesn't happen.
=> Correctly calculate chosen label hour

daterangepicker.js
Hey, I have been using https://github.com/skratchdot/react-bootstrap-daterangepicker which wraps daterangepicker, we've migrated our site to React 16.4 from React 15 and encountered an error with the base library.
"TypeError: moment is not a function"
It appears when inserted into the webpack build, the library tries to use 'moment' however it receives an object instead of moment, the object contains a 'default' property that is the actual moment method.
I've added a check when the package is built via webpack to check if moment is not a function and whether it has a default property, and if so, override moment with moment.default and continue as usual.
This change fixed the error on our project and we're using a forked version for the meantime.
Thanks in advance for this awesome library.
=> Fix TypeError: moment is not a function(…)

daterangepicker.css
- fix(#1783): fixed a css bug that occurrence when `locale.direction` is ` ltr`
Now it works! 😃
=> fix(#1783): fixed a css bug that occurrence when `locale.direction` is ` ltr`

daterangepicker.js
I recently made a modification to the `daterangepicker.js` file to handle an issue when setting the option `timePickerIncrement` to 15 minutes. Every time the minDate was in minutes 46-59, the calendars rendered "NaN" for every date.
All I did was check if the minutes was "NaN" and forced it to use the last option in the minutes select, and it seemed to do the trick.
Thanks for your consideration!
=> Fix NaN when using timePickerIncrement

daterangepicker.js
renderTimePicker fix if the selected minute or second are 0. If selected.minute() is 0, that would return false and default to timeSelector. Whatever that might be.
=> renderTimePicker fix

daterangepicker.js
Currently there's no way to distinguish a disabled date from one that's disabled and just from the prev/next month via css.
You can determine not disabled ends with `td.available.off`.   Items that are disabled and not current month end up with the class "off off disabled" which can't be selected for specifically.   The isCustom is unable to be used to distinguish this either since it's not passed if it's the left or right calendar.
=> Add identifying class to dates from prev/next month on calendar

daterangepicker.js
Reverts dangrossman/daterangepicker#1588
This fixes one day but breaks the day before, on top of breaking time consistency with all the other dates all as detailed out here:
https://github.com/dangrossman/daterangepicker/issues/1890#issuecomment-450014401
=> Revert "Fix for issue #1587"

daterangepicker.js
The bug happen because the old code assumed that the offset gonna be
smaller than 0 or bigger than the screen width when the calendar exceed
the screen. But what actually happened is that the browser change
the width of the pop-up to the remaining width.
Here is the sandbox to demo the fix https://codesandbox.io/s/mm4xjx4x2y
Fixed: #1856
=> Fix broken layout when the picker is too close to the window edge

daterangepicker.js
As of jQuery 3.0, removeAttr() no longer sets properties to false and so using popper.js with Bootstrap 4.x is giving an error for removeAttr usage. This is a fix for this issue.
=> Fix for popper.js setAttribute issue

daterangepicker.js
When compressing `daterangepicker.js` as part of an asset build pipeline using YUICompressor, this file breaks JS compilation due to invalid usage of the reserved keyword `default`
=> Usage of JS reserved word default breaks YUICompressor

daterangepicker.js
As found in #1872, the auto apply option is ignored when using a single date picker, meaning that autoApply is by default set. This change allows for the autoApply config option to be used even in a singleDatePicker.
=> Allow for singleDatePicker to disable autoApply
